# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
    push:
    pull_request:
    workflow_dispatch:
defaults:
    run:
        shell: bash
env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    DOTNET_NOLOGO: true
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
                cfg:
                    - Debug
                    - Release
                mode:
                    - Fast
                    - Safe
                    - Small
                exclude:
                    - cfg: Debug
                      mode: Fast
                    - cfg: Debug
                      mode: Small
        runs-on: ${{ matrix.os }}
        steps:
            - name: Clone repository
              uses: actions/checkout@v2.3.4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Extract .NET version
              id: dotnet
              run: |
                  echo ::set-output name=version::$(jq .sdk.version global.json -r)
            - name: Set up .NET
              uses: actions/setup-dotnet@v1.8.0
              with:
                  dotnet-version: ${{ steps.dotnet.outputs.version }}
            - name: Restore SDK
              run: |
                  dotnet tool restore
                  dotnet restore
            - name: Format SDK
              run: |
                  dotnet format --check -f
            - name: Build SDK
              run: |
                  dotnet build --no-restore
            - name: Clean SDK
              run: |
                  dotnet clean
            - name: Restore samples
              run: |
                  dotnet restore src/samples
            - name: Build samples
              run: |
                  dotnet build src/samples -c ${{ matrix.cfg }} --no-restore -p:ReleaseMode=${{ matrix.mode }} -v:d
            - name: Test samples
              run: |
                  dotnet test src/samples -c ${{ matrix.cfg }} --no-restore -p:ReleaseMode=${{ matrix.mode }} -v:d
            - name: Pack samples
              run: |
                  dotnet pack src/samples -c ${{ matrix.cfg }} --no-build -v:d
            - name: Publish samples
              run: |
                  dotnet publish src/samples -c ${{ matrix.cfg }} --no-build -v:d
            - name: Clean samples
              run: |
                  dotnet clean src/samples -c ${{ matrix.cfg }} -v:d
